### ISSUE TITLE
Dúvidas do projeto

### ISSUE THREAD

**Issue by gilsondev** [culturagovbr/bot_salic_notifica#1]
Olá,

Eu estou dando uma olhada no README e no código do projeto e tenho algumas dúvidas:

 - Qual é a versão exata do Python? (e.g.: 3.5, 3.6, 3.6.2)
 - O uso do SQLite é somente para definir um registro dos últimos quinze projetos exibidos?
 - O que seria as colunas `PRONAC`, `id` e `cod`?
- Para que serve o `checkExists` na [linha 17](https://github.com/gilsondev/bot_salic_notifica/blob/master/bot.py#L17)?
 - Jà cogitaram de usar o pacote `requests`? Ele deixa o seu código mais conciso e mais legível que o urllib, e já prepara alguns detalhes para vocês, como o `.decode` que fazem na [linha 23](https://github.com/gilsondev/bot_salic_notifica/blob/master/bot.py#L23) por exemplo.
 - Vendo a URL da chamada, vocês já limitam em buscar os últimos quinze projetos. Se a minha segunda pergunta for um sim, realmente precisa disso e porque?

A idéia é entender melhor para ajudar em algumas refatorações que irei enviar um PR como sugestões de melhorias.

**Comment by guiamado** [comment]
Olá Gilson,

Estamos usando a versão 3.5.3 do Python.
O SQLite é utilizado como uma espécie de buffer, onde o código confere os últimos 15 projetos.
A coluna PRONAC é o sequencial dos projetos que são aprovados no sistema Salic (versalic.cultura.gov.br). Já a coluna id é um indice do sequencial (PRONAC), e será necessária para fazer as atualizações no banco. A coluna cod foi a maneira que achamos para identificar os campos onde estão armazenados os sequenciais que serão aferidos pelo código. Por isso criamos a variável "checkExists", pois na documentação do SQLite quando se faz um SELECT é retornado um número booleano 0 ou 1. No caso do retorno ser 0 ou "[(0, )]" em todas as posições da sequencia de PRONACs analisados no banco, esse número não existe armazenado e cria a condição para enviar a mensagem e o número é armazenado, atualizando a coluna. Se o número PRONAC existe no banco, uma das tuplas retornará 1 ou [(1,)] indicando que nada acontecerá.
Tentei utilizar uma vez o pacote requests e tive problemas, então procurei outras maneiras para não perder muito nessa parte.
A gente limita os últimos 15 projetos, porém o retorno não necessariamente trará projetos que ainda não foram enviados como mensagem. Esse é o motivo principal por trás da criação do banco de dados e o sistema de verificação.
