### ISSUE TITLE
Melhorar template textual

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/bot_salic_notifica#5]
![screenshot_2017-11-11-11-46-24-080_org telegram plus](https://user-images.githubusercontent.com/1244443/32690049-ffe09bac-c6d6-11e7-82a1-191a262f8965.png)
Para dar mais visibilidade, reordenar os metadados para:
* None
* Resumo 
* Cidade
* Área 
* Segmento
* Valor

Não apresentar o Pronac. Não utilizar o "do projeto" nas labels. Ou seja, ao invés de Nome do Projeto, apenas "Nome"

**Comment by guiamado** [comment]
Feitas mudanças sugeridas no template da mensagem.
